### ISSUE TITLE
Error with server

### ISSUE THREAD

**Issue by macjl** [Beaujr/nmap_prometheus#41]
Hello. I’m facing an issue with this tool. Here is the log as client side  

```2023/01/16` 21:46:02 Bulk GRPC report: 53
2023/01/16 21:46:12 unable to run GRPC report: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2023/01/16 21:46:12 unable to run GRPC report: rpc error: code = DeadlineExceeded desc = context deadline exceeded```

And nothing on server side. 

And the docker-compose : 
```nmap_prometheus_client:
    image: beaujr/nmap_prometheus:client
    command: '-server=localhost:50051 -subnet=192.168.50.0/24'
    network_mode: host
    restart: always

  nmap_prometheus_server:
    image: beaujr/nmap_prometheus:server
    ports:
      - 50051:50051
      - 2112:2112
    volumes:
      - ~/dockers/domotic/data/nmap_prometheus_exporter/config:/config
    command: '-debug=true'
    restart: always ```

Can someone help me ?

**Comment by Beaujr** [comment]
Hi, I'll look into it tomorrow. I didn't realise anyone else was using this
tool. Feel free to email me and I can try to help your use case further.

**Comment by macjl** [comment]
For now, i’m not using it, because I can’t get it working… But your tool seems interesting to monitor my network !

Here is a more complete client log if needed : 

```pi@minii5:~/dockers/domotic$ docker logs domotic-nmap_prometheus_client-1 
2023/01/17 19:41:14 Application Starting
2023/01/17 19:41:14 Local Interface Mac (0C:4D:E9:CA:A8:A9) Ip (192.168.50.100)
2023/01/17 19:41:14 Local Interface Mac (02:42:10:01:89:95) Ip (172.27.0.1)
2023/01/17 19:41:14 Local Interface Mac (02:42:45:03:16:F9) Ip (172.22.0.1)
2023/01/17 19:41:14 Local Interface Mac (02:42:3D:37:88:C1) Ip (172.21.0.1)
2023/01/17 19:41:14 Local Interface Mac (02:42:10:2A:3C:5B) Ip (172.17.0.1)
2023/01/17 19:41:14 Local Interface Mac (02:42:E9:12:89:5F) Ip (172.20.0.1)
2023/01/17 19:41:14 Local Interface Mac (02:42:CB:3C:89:45) Ip (172.18.0.1)
2023/01/17 19:41:14 Local Interface Mac (02:42:F7:B9:F4:F4) Ip (172.19.0.1)
2023/01/17 19:41:16 Bulk GRPC report: 32
2023/01/17 19:41:26 unable to run GRPC report: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2023/01/17 19:41:26 unable to run GRPC report: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2023/01/17 19:41:31 Bulk GRPC report: 32
2023/01/17 19:41:34 unable to run GRPC report: rpc error: code = Unavailable desc = timed out waiting for server handshake
2023/01/17 19:41:34 unable to run GRPC report: rpc error: code = Unavailable desc = timed out waiting for server handshake ```

**Comment by Beaujr** [comment]
Are you running on Macos, Linux or windows? I can look at replicating in a
VM and trying to solve your issues.

**Comment by macjl** [comment]
It’s running in Linux x86-64. I can also try with a Rpi4 if needed.

**Comment by macjl** [comment]
Just tried on Raspberry Pi 4, and same issue.

**Comment by Beaujr** [comment]
Cool.. it's probably because I've updated the images out of sync with this
compose config. I also have a raspberry pi 4. I'll reply to this thread
when I have a working pr

**Comment by macjl** [comment]
Hello,

Are you still working on it ?

**Comment by Beaujr** [comment]
Yeah, I still have it running on my local network. But I have done some modifications to run it on mqtt. Would you like a new version published?

**Comment by macjl** [comment]
I asked ChatGPT to develop a similar exporter, and it did it, with all my needs !
So I will not use your exporter now. Thank you anyway !
